### PR TITLE
If using a mouse, handle piece dragging like lichess web.

### PR DESCRIPTION
**Pull request by safraser**
Currently when dragging a piece by touch there is a large circular shadow showing the target square and the dragged piece is offset so everything is visible despite the finger in the way. However if a mouse is used either on a tablet or in a desktop app this looks strange. 

This PR makes the behaviour closer to normal chess applications when using the mouse but keeping the same behaviour for touch screens, specifically:
* the dragged piece follows the cursor
* instead of a large circle, the target square is highlighted.

This could be further refined by making only legal target squares be highlighted.

### CODE REVIEW

**Comment by HaonRekcef** [comment]
Currently, users have the option to disable the magnified dragging effect under Settings > Board. So the piece already follows the cursor if the user wants, however I see the point for the circle and square highlighting.

**Comment by veloce** [comment]
Thanks for this initiative!

This PR is missing the tests for this new feature. All the logic in this package should be tested, because it is very important for a chess app. Right now there is no test for the shadow circle when dragging a piece, I believe. This is the opportunity to add one and add tests for the mouse too.

**Comment by safraser** [comment]
I'm a bit busy in the immediate future but will look into adding the tests. I'm not that familiar with flutter at the moment so it will likely take me a bit of time anyway.

**Comment by veloce** [comment]
Actually, I used your code and added some more logic so we can also have this behaviour in touch devices for those who want to.

**Pull request merged**
