### PR TITLE
Add Caliente, kiwen-suwi and mpchess piece sets

### LINKED ISSUE #14: Add caliente piece set
A new piece set called caliente was added to lila: https://github.com/lichess-org/lila/issues/13107
Caliente piece set repository: https://github.com/avi-0/caliente

### PR DESCRIPTION
**Pull request by tedzards509**
Resolves #14 

+ dependency updates

### CODE REVIEW

**Comment by veloce** [comment]
@tedzards509 there are some conflicts here, thx.

**Comment by tedzards509** [comment]
Should be resolved by reverting the dependency update as it has been done already in commit 5cf424a

**Comment by tedzards509** [comment]
I will have to refactor to comply with #21 

I also found even more missing piece sets. I'll add
- caliente
- mpchess
- kiwen-suwi

While mono is in https://github.com/lichess-org/lila/tree/master/public/piece, I have not seen it used on the lichess website, so it feels pointless to add. Let me know if I should add it non the less. (mono is a piece set where every piece is grey)

**Comment by tedzards509** [comment]
Done.

**Comment by tedzards509** [comment]
Done and reopened

**Comment by niklasf** [comment]
Mono is used only to render material difference:

image

**Review by veloce — APPROVED** [review]

**Pull request merged**
